global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        regex: '(.*):9121'
        target_label: instance
        replacement: '$1'
